### ISSUE TITLE
接收数据卡死

### ISSUE THREAD

**Issue by stduent-vehicle** [wulang584513/ARS548-demo#2]
你好，谢谢你的工作，我在运行代码时，发现在下面这一行就卡住了，不知道你有没有遇到过？

` len = recvfrom(socket_server_fd, data, 40000, 0, (struct sockaddr *) &group_addr, &addr_len);`

**Comment by amineabm** [comment]
@Gang-Chen-China Where did you find the code ?

**Comment by stduent-vehicle** [comment]
@amineabm 

https://github.com/wulang584513/ARS548-demo/tree/master

**Comment by maomao0220** [comment]
您好，请问你跑通了吗？请教一下您是怎样配置的呢？
我ubuntu18.04 ，直接用的以太网转换器接到笔记本电脑，没有用交换机，设置了笔记本的IP和Vlan，但是这里我不确定VLAN是不是设置对了。我使用wireshark可以收到数据，但是用这个程序跑的时候没有任何数据输出？请问您解决了吗?
@Gang-Chen-China @wulang584513 @amineabm

**Comment by stduent-vehicle** [comment]
> 

@maomao0220 这个没跑通，我改用libpcap库去抓的包，然后用它的data_process文件去解析的，也能工作。

**Comment by maomao0220** [comment]
@Gang-Chen-China 您好，可以分享一下您的源码吗？非常感谢 1357971047@qq.com

**Comment by maomao0220** [comment]
@Gang-Chen-China您好，可以加微信私聊吗？想问 一下VLAN的设置

**Comment by stduent-vehicle** [comment]
> @Gang-Chen-China 您好，可以分享一下您的源码吗？非常感谢 [1357971047@qq.com](mailto:1357971047@qq.com)

@maomao0220 参考这个链接，可以捕获以太网包：https://blog.51cto.com/u_3002289/5720954

**Comment by maomao0220** [comment]
@Gang-Chen-China 您好哥，我用的ubuntu18.04 ，请问您是怎么配置IP和vlan的？我这试了几种方法都不行，ping不同548雷达

**Comment by stduent-vehicle** [comment]
> @Gang-Chen-China 您好哥，我用的ubuntu18.04 ，请问您是怎么配置IP和vlan的？我这试了几种方法都不行，ping不同548雷达

@maomao0220 你就用libpcap去抓网卡的数据包，然后再解析，套接字我试了也接收不了。

**Comment by s0966066980** [comment]
請問你有順利的連接上了嗎？
我配置好IP和vlan,但依舊無法順利連接上

> 你好，謝謝你的工作，我在運行代號時，發現下面這行就卡住了，不知道你有沒有遇到過？
> 
> ` len = recvfrom(socket_server_fd, data, 40000, 0, (struct sockaddr *) &group_addr, &addr_len);`

**Comment by s0966066980** [comment]
> > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> 
> @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954

您好,想詢問您具體是如何實現的,我嘗試使用libpcap去抓網卡的數據包,但不知道如何應用data_process文件來去解析

**Comment by Gang-Chen-China** [comment]
> 
你是不是没有雷达协议手册？data_process处理的是udp内容，libpcap获得的数据包含以太网头，你需要提取出来udp数据，这个要根据雷达协议手册才好处理。

**Comment by stduent-vehicle** [comment]
> > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > 
> > 
> > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> 
> 您好,想詢問您具體是如何實現的,我嘗試使用libpcap去抓網卡的數據包,但不知道如何應用data_process文件來去解析

你是不是没有雷达协议手册？data_process处理的是udp内容，libpcap获得的数据包含以太网头，你需要提取出来udp数据，这个要根据雷达协议手册才好处理。

**Comment by s0966066980** [comment]
> > > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > > 
> > > 
> > > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> > 
> > 
> > 你好，想問你的工具是如何實現的，我嘗試使用libpcap去抓網卡的數據包，但不知道如何使用data_process文件去解析
> 
> 你是不是沒有雷達協議手冊？data_process處理的是udp內容，libpcap獲得的數據包以太網頭，你需要提取來udp數據，這個要根據雷達協議手冊才好處理。

您好,我是有一份這個(ARS548_IO Stand 20.5.2022 1. Update - 通信协议（适配固件版本为v5.48.1）.xlsx),有雷達的協議資料之類的東西,我目前能使用vlan的方式連接好,也能得撈到void ProcessRadarData(char *data, int len)所需的case,但不知道如何與ars548_process_node.cpp去連接,使用ars548_process_node_bck.cpp好像也不是能直接使用udp連接上,這方面的技術不太熟悉,想請教您使用的流程.感謝您

**Comment by Gang-Chen-China** [comment]
> > > > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > > > 
> > > > 
> > > > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> > > 
> > > 
> > > 你好，想問你的工具是如何實現的，我嘗試使用libpcap去抓網卡的數據包，但不知道如何使用data_process文件去解析
> > 
> > 
> > 你是不是沒有雷達協議手冊？data_process處理的是udp內容，libpcap獲得的數據包以太網頭，你需要提取來udp數據，這個要根據雷達協議手冊才好處理。
> 
> 您好,我是有一份這個(ARS548_IO Stand 20.5.2022 1. Update - 通信协议（适配固件版本为v5.48.1）.xlsx),有雷達的協議資料之類的東西,我目前能使用vlan的方式連接好,也能得撈到void ProcessRadarData(char *data, int len)所需的case,但不知道如何與ars548_process_node.cpp去連接,使用ars548_process_node_bck.cpp好像也不是能直接使用udp連接上,這方面的技術不太熟悉,想請教您使用的流程.感謝您
你邮箱多少？

**Comment by stduent-vehicle** [comment]
> > > > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > > > 
> > > > 
> > > > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> > > 
> > > 
> > > 你好，想問你的工具是如何實現的，我嘗試使用libpcap去抓網卡的數據包，但不知道如何使用data_process文件去解析
> > 
> > 
> > 你是不是沒有雷達協議手冊？data_process處理的是udp內容，libpcap獲得的數據包以太網頭，你需要提取來udp數據，這個要根據雷達協議手冊才好處理。
> 
> 您好,我是有一份這個(ARS548_IO Stand 20.5.2022 1. Update - 通信协议（适配固件版本为v5.48.1）.xlsx),有雷達的協議資料之類的東西,我目前能使用vlan的方式連接好,也能得撈到void ProcessRadarData(char *data, int len)所需的case,但不知道如何與ars548_process_node.cpp去連接,使用ars548_process_node_bck.cpp好像也不是能直接使用udp連接上,這方面的技術不太熟悉,想請教您使用的流程.感謝您


你邮箱多少？

**Comment by s0966066980** [comment]
> > > > > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > > > > 
> > > > > 
> > > > > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> > > > 
> > > > 
> > > > 你好，想問你的工具是如何實現的，我嘗試使用libpcap去抓網卡的數據包，但不知道如何使用data_process文件去解析
> > > 
> > > 
> > > 你是不是沒有雷達協議手冊？data_process處理的是udp內容，libpcap獲得的數據包以太網頭，你需要提取來udp數據，這個要根據雷達協議手冊才好處理。
> > 
> > 
> > 您好,我是有一份這個(ARS548_IO Stand 20.5.2022 1. Update - 通信协议（适配固件版本为v5.48.1）.xlsx),有雷達的協議資料之類的東西,我目前能使用vlan的方式連接好,也能得撈到void ProcessRadarData(char *data, int len)所需的case,但不知道如何與ars548_process_node.cpp去連接,使用ars548_process_node_bck.cpp好像也不是能直接使用udp連接上,這方面的技術不太熟悉,想請教您使用的流程.感謝您
> 
> 你邮箱多少？

s0966066980@gmail.com

感謝您的回覆！

**Comment by zouyoucheng27** [comment]
我已经通过libpcap拿到数据了，并且解析了雷达的数据，请问怎样跟雷达建立通讯，将配置信息与自身车辆的运动信息输入给雷达，通过socket好像无法与雷达建立通讯

**Comment by s0966066980** [comment]
> > > > > > @Gang-Chen-China您好，可以分享一下您的源碼嗎？非常感謝[1357971047@qq.com](mailto:1357971047@qq.com)
> > > > > 
> > > > > 
> > > > > @maomao0220參考這個鏈接，可以獲取以太網包：https://blog.51cto.com/u_3002289/5720954
> > > > 
> > > > 
> > > > 你好，想問你的工具是如何實現的，我嘗試使用libpcap去抓網卡的數據包，但不知道如何使用data_process文件去解析
> > > 
> > > 
> > > 你是不是沒有雷達協議手冊？data_process處理的是udp內容，libpcap獲得的數據包以太網頭，你需要提取來udp數據，這個要根據雷達協議手冊才好處理。
> > 
> > 
> > 您好,我是有一份這個(ARS548_IO Stand 20.5.2022 1. Update - 通信协议（适配固件版本为v5.48.1）.xlsx),有雷達的協議資料之類的東西,我目前能使用vlan的方式連接好,也能得撈到void ProcessRadarData(char *data, int len)所需的case,但不知道如何與ars548_process_node.cpp去連接,使用ars548_process_node_bck.cpp好像也不是能直接使用udp連接上,這方面的技術不太熟悉,想請教您使用的流程.感謝您
> 
> 你邮箱多少？

您好,請問您知道如何設置radar的位置嗎?我目前可以使用程式碼了,但偵測永遠是hazard or unknown
