### ISSUE TITLE
ARS548 Drvier

### ISSUE THREAD

**Issue by wjjjjyourFA** [wulang584513/ARS548-demo#4]
大佬好，请问大佬的ars548_demo程序还会再分享吗。###

**Comment by Guoc0529** [comment]
你好，请问有ARS548的rosbag吗，想采购不知道数据格式是什么样的？能加个好友吗18406583098

**Comment by wjjjjyourFA** [comment]
我这里在该git作者的基础上已经改好对应的5.48.1、5.48.4固件的代码，并且取消了对交换机的VLAN需求，仅需要X86安装VLAN并配置即可使用，ARM上无法使用，原因未知。感谢大佬的代码框架。
